# One Model Against All Benchmarks

This notebook runs one configurable model against every benchmark registered in `runners.full_suite.FULL_BENCHMARK_CLASSES`. It is set up for RunPod and local execution, records failures per benchmark, and resumes without overwriting completed results.

The default model is Qwen2.5-VL 3B. Set `DATASET_SMOKE_TEST=1` to use the repository's existing open-weight LLaVA-Gemma 2B model for a lighter end-to-end test. Even with one sample per benchmark, this run downloads many datasets and includes image, multi-image, and video tasks. Set `HF_TOKEN` in the RunPod environment for gated datasets such as ImageNet.

LSUN, TAD66K, and ShareGPT-4o-Image now use lightweight Hugging Face access by default: LSUN caches small validation LMDB archives, TAD66K range-reads only requested JPEG members, and ShareGPT streams WebDataset rows. The corresponding `*_ROOT` variables remain optional local-data overrides.

## 1. Repository and run configuration

In [1]:
from pathlib import Path
import getpass
import json
import os
import subprocess
import sys

REPO_URL = "https://github.com/samhatescoding/transformers.git"
REPO_BRANCH = "main"

candidate_roots = [Path.cwd(), *Path.cwd().parents]
REPO_ROOT = next((path for path in candidate_roots if (path / "models").is_dir()), None)
if REPO_ROOT is None:
    clone_parent = Path("/workspace") if Path("/workspace").is_dir() else Path.cwd()
    REPO_ROOT = clone_parent / "transformers"
    if REPO_ROOT.exists() and not (REPO_ROOT / "models").is_dir():
        raise RuntimeError(f"Clone target exists but is not this repository: {REPO_ROOT}")
    if not REPO_ROOT.exists():
        subprocess.run(
            ["git", "clone", "--branch", REPO_BRANCH, "--single-branch", REPO_URL, str(REPO_ROOT)],
            check=True,
        )
REPO_ROOT = REPO_ROOT.resolve()

requirements_path = REPO_ROOT / "requirements.txt"
%pip install -q -r "$requirements_path"
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import pandas as pd
import torch
from huggingface_hub import login

DATASET_SMOKE_TEST = os.getenv("DATASET_SMOKE_TEST", "0") == "1"

# Best practice on RunPod: add HF_TOKEN under Pod > Environment Variables.
# If it is absent, this prompt is hidden and only lasts for the current kernel.
HF_TOKEN = os.getenv("HF_TOKEN") or os.getenv("HUGGING_FACE_HUB_TOKEN")
if not HF_TOKEN and not DATASET_SMOKE_TEST:
    entered_token = getpass.getpass("HF token (press Enter to continue without one): ").strip()
    if entered_token:
        HF_TOKEN = entered_token
        os.environ["HF_TOKEN"] = entered_token
if HF_TOKEN:
    login(token=HF_TOKEN, add_to_git_credential=False)

NUM_SAMPLES = 1
OVERWRITE = False
RUN_NAME = "dataset_smoke_test" if DATASET_SMOKE_TEST else "qwen25vl3b_all_benchmarks"
OUTPUT_DIR = REPO_ROOT / "results" / RUN_NAME
SUMMARY_PATH = OUTPUT_DIR / "run_summary.json"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print(f"Repository: {REPO_ROOT}")
print(f"Results: {OUTPUT_DIR}")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"GPU: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'none'}")
print(f"LLaVA-Gemma 2B smoke test: {DATASET_SMOKE_TEST}")
print(f"HF authentication: {'configured' if HF_TOKEN else 'not configured'}")
for variable in ("LSUN_ROOT", "TAD66K_ROOT", "SHAREGPT4O_IMAGE_ROOT"):
    print(f"{variable}: {'configured (local override)' if os.getenv(variable) else 'using Hugging Face source'}")

Repository: C:\Users\Samuel\Documents\GitHub\transformers
Results: C:\Users\Samuel\Documents\GitHub\transformers\results\dataset_smoke_test
CUDA available: False
GPU: none
LLaVA-Gemma 2B smoke test: True
HF authentication: not configured
LSUN_ROOT: using Hugging Face source
TAD66K_ROOT: using Hugging Face source
SHAREGPT4O_IMAGE_ROOT: using Hugging Face source

C:\Users\Samuel\AppData\Roaming\Python\Python314\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 2. Load the selected model

Replace `Qwen25VL3B` with another public model class if needed. For API-backed wrappers, set the corresponding provider key before executing this cell.

In [2]:
from models import LlavaGemma2B, Qwen25VL3B
from runners import ModelRun

if DATASET_SMOKE_TEST:
    MODEL_NAME = "llava-gemma-2b"
    model_run = ModelRun.from_factory(
        MODEL_NAME,
        LlavaGemma2B,
        max_new_tokens=32,
    )
else:
    MODEL_NAME = "qwen2.5-vl-3b-instruct"
    model_run = ModelRun.from_factory(
        MODEL_NAME,
        Qwen25VL3B,
        max_new_tokens=32,
    )
model_run

Loading LLaVA processor...

The image processor of type `CLIPImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

Loading LLaVA model...

Loading weights:   0%|          | 0/559 [00:00<?, ?it/s]

Loading weights:   0%|          | 1/559 [00:05<50:56,  5.48s/it]

Loading weights:   1%|          | 3/559 [00:05<13:30,  1.46s/it]

Loading weights:   7%|▋         | 39/559 [00:05<00:39, 13.27it/s]

Loading weights:  23%|██▎       | 129/559 [00:06<00:09, 47.33it/s]

Loading weights:  26%|██▋       | 147/559 [00:06<00:10, 40.40it/s]

Loading weights:  29%|██▊       | 160/559 [00:07<00:11, 34.03it/s]

Loading weights:  35%|███▍      | 193/559 [00:07<00:07, 48.99it/s]

Loading weights:  42%|████▏     | 232/559 [00:07<00:04, 73.33it/s]

Loading weights:  49%|████▉     | 273/559 [00:08<00:02, 99.11it/s]

Loading weights:  55%|█████▍    | 305/559 [00:08<00:02, 123.04it/s]

Loading weights:  61%|██████▏   | 343/559 [00:08<00:01, 158.01it/s]

Loading weights:  67%|██████▋   | 372/559 [00:08<00:01, 166.66it/s]

Loading weights:  75%|███████▍  | 417/559 [00:08<00:00, 183.28it/s]

Loading weights:  83%|████████▎ | 465/559 [00:08<00:00, 221.32it/s]

Loading weights:  89%|████████▉ | 497/559 [00:08<00:00, 238.87it/s]

Loading weights:  97%|█████████▋| 545/559 [00:08<00:00, 245.77it/s]

Loading weights: 100%|██████████| 559/559 [00:08<00:00, 62.16it/s]

Device map: None

ModelRun(name='llava-gemma-2b', model=<models.llava_gemma_2b.LlavaGemma2B object at 0x000001CEB5412510>, load_time_seconds=16.250638900033664)

## 3. Instantiate every registered benchmark

In [3]:
from runners.full_suite import FULL_BENCHMARK_CLASSES

print(f"Benchmarks: {len(FULL_BENCHMARK_CLASSES)}")
[benchmark_class.benchmark_name for benchmark_class in FULL_BENCHMARK_CLASSES]

Benchmarks: 40

['blip3o_60k',
 'conceptual_captions',
 'conceptual_captions_caption',
 'cityscapes',
 'dfdc',
 'diffusiondb',
 'docvqa',
 'fairface',
 'fashion_mnist',
 'flickr30k',
 'flickr30k_entities',
 'flyingthings3d',
 'gqa',
 'hdtf',
 'hq_edit',
 'imagenet1k',
 'imgedit',
 'inaturalist',
 'internvid',
 'kinetics',
 'laion400m',
 'laion5b',
 'lsun',
 'lvis',
 'mscoco',
 'mscoco_caption',
 'mvtec_ad',
 'magicbrush',
 'openimages_v4',
 'openimages_v4_detection',
 'openvid1m',
 'pick_a_pic',
 'places',
 'sharegpt4o_image',
 'tad66k',
 'textcaps',
 'ucf101',
 'visual_cot',
 'visual_genome',
 'vqav2']

## 4. Run the complete matrix

With one model, the number of pairs equals the number of registered benchmarks. Each pair is executed through the canonical `run_benchmark_matrix` runner. Calling it one pair at a time lets the notebook record unavailable datasets in `run_summary.json` and resume without rerunning completed results.

In [4]:
import traceback

from runners import BenchmarkRun, run_benchmark_matrix

summaries = []
for benchmark_class in FULL_BENCHMARK_CLASSES:
    benchmark_name = str(benchmark_class.benchmark_name)
    result_path = OUTPUT_DIR / f"{MODEL_NAME}_{benchmark_name}.json"

    if result_path.exists() and not OVERWRITE:
        entry = {
            "model": MODEL_NAME,
            "benchmark": benchmark_name,
            "status": "skipped",
            "results_path": str(result_path),
        }
    else:
        print(f"[RUN] {MODEL_NAME} / {benchmark_name}", flush=True)
        try:
            benchmark = benchmark_class(streaming=True)
            model_run.model.max_new_tokens = benchmark.default_max_new_tokens
            sample_count = min(NUM_SAMPLES, 9) if benchmark_name == "ucf101" else NUM_SAMPLES
            pair_summary = run_benchmark_matrix(
                models=[model_run],
                benchmark_runs=[BenchmarkRun(benchmark=benchmark, num_samples=sample_count)],
                output_dir=OUTPUT_DIR,
            )[0]
            entry = {**pair_summary, "status": "ok"}
        except Exception as exc:
            entry = {
                "model": MODEL_NAME,
                "benchmark": benchmark_name,
                "status": "error",
                "error": f"{type(exc).__name__}: {exc}",
                "traceback": traceback.format_exc(),
            }

    summaries.append(entry)
    SUMMARY_PATH.write_text(json.dumps(summaries, indent=2), encoding="utf-8")
    print(f"[{entry['status'].upper()}] {MODEL_NAME} / {benchmark_name}", flush=True)

summary_df = pd.DataFrame(summaries)
summary_df

[RUN] llava-gemma-2b / blip3o_60k

[ERROR] llava-gemma-2b / blip3o_60k

[RUN] llava-gemma-2b / conceptual_captions

[OK] llava-gemma-2b / conceptual_captions

[RUN] llava-gemma-2b / conceptual_captions_caption

[OK] llava-gemma-2b / conceptual_captions_caption

[RUN] llava-gemma-2b / cityscapes

[OK] llava-gemma-2b / cityscapes

[RUN] llava-gemma-2b / dfdc

[OK] llava-gemma-2b / dfdc

[RUN] llava-gemma-2b / diffusiondb

[ERROR] llava-gemma-2b / diffusiondb

[RUN] llava-gemma-2b / docvqa

[OK] llava-gemma-2b / docvqa

[RUN] llava-gemma-2b / fairface

[OK] llava-gemma-2b / fairface

[RUN] llava-gemma-2b / fashion_mnist

[OK] llava-gemma-2b / fashion_mnist

[RUN] llava-gemma-2b / flickr30k

'The read operation timed out' thrown while requesting GET https://huggingface.co/datasets/nlphuji/flickr30k/resolve/cd91f9a00273ce2e1584511cba8c10b917c488a3/TEST/test/0000.parquet

Retrying in 1s [Retry 1/5].

[OK] llava-gemma-2b / flickr30k

[RUN] llava-gemma-2b / flickr30k_entities

[OK] llava-gemma-2b / flickr30k_entities

[RUN] llava-gemma-2b / flyingthings3d

'The read operation timed out' thrown while requesting GET https://huggingface.co/datasets/infinity1096/flyingthings3d_processed/resolve/d8f06579a500615105c1a9698d0a8436c5dc6f50/flow/train/0_127.h5

Retrying in 1s [Retry 1/5].

'The read operation timed out' thrown while requesting GET https://huggingface.co/datasets/infinity1096/flyingthings3d_processed/resolve/d8f06579a500615105c1a9698d0a8436c5dc6f50/flow/train/0_127.h5

Retrying in 1s [Retry 1/5].

'_ssl.c:1063: The handshake operation timed out' thrown while requesting GET https://huggingface.co/datasets/infinity1096/flyingthings3d_processed/resolve/d8f06579a500615105c1a9698d0a8436c5dc6f50/flow/train/0_127.h5

Retrying in 2s [Retry 2/5].

'_ssl.c:1063: The handshake operation timed out' thrown while requesting GET https://huggingface.co/datasets/infinity1096/flyingthings3d_processed/resolve/d8f06579a500615105c1a9698d0a8436c5dc6f50/flow/train/0_127.h5

Retrying in 4s [Retry 3/5].

'_ssl.c:1063: The handshake operation timed out' thrown while requesting GET https://huggingface.co/datasets/infinity1096/flyingthings3d_processed/resolve/d8f06579a500615105c1a9698d0a8436c5dc6f50/flow/train/0_127.h5

Retrying in 8s [Retry 4/5].

'_ssl.c:1063: The handshake operation timed out' thrown while requesting GET https://huggingface.co/datasets/infinity1096/flyingthings3d_processed/resolve/d8f06579a500615105c1a9698d0a8436c5dc6f50/flow/train/0_127.h5

Retrying in 8s [Retry 5/5].

[ERROR] llava-gemma-2b / flyingthings3d

[RUN] llava-gemma-2b / gqa

[OK] llava-gemma-2b / gqa

[RUN] llava-gemma-2b / hdtf

[ERROR] llava-gemma-2b / hdtf

[RUN] llava-gemma-2b / hq_edit

[OK] llava-gemma-2b / hq_edit

[RUN] llava-gemma-2b / imagenet1k

[OK] llava-gemma-2b / imagenet1k

[RUN] llava-gemma-2b / imgedit

[ERROR] llava-gemma-2b / imgedit

[RUN] llava-gemma-2b / inaturalist

[OK] llava-gemma-2b / inaturalist

[RUN] llava-gemma-2b / internvid

[ERROR] llava-gemma-2b / internvid

[RUN] llava-gemma-2b / kinetics

[ERROR] llava-gemma-2b / kinetics

[RUN] llava-gemma-2b / laion400m

[ERROR] llava-gemma-2b / laion400m

[RUN] llava-gemma-2b / laion5b

[ERROR] llava-gemma-2b / laion5b

[RUN] llava-gemma-2b / lsun

[OK] llava-gemma-2b / lsun

[RUN] llava-gemma-2b / lvis

C:\Users\Samuel\AppData\Roaming\Python\Python314\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Samuel\.cache\huggingface\hub\datasets--winvoker--lvis. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

[ERROR] llava-gemma-2b / lvis

[RUN] llava-gemma-2b / mscoco

[OK] llava-gemma-2b / mscoco

[RUN] llava-gemma-2b / mscoco_caption

[OK] llava-gemma-2b / mscoco_caption

[RUN] llava-gemma-2b / mvtec_ad

[OK] llava-gemma-2b / mvtec_ad

[RUN] llava-gemma-2b / magicbrush

[ERROR] llava-gemma-2b / magicbrush

[RUN] llava-gemma-2b / openimages_v4

[OK] llava-gemma-2b / openimages_v4

[RUN] llava-gemma-2b / openimages_v4_detection

[OK] llava-gemma-2b / openimages_v4_detection

[RUN] llava-gemma-2b / openvid1m

[ERROR] llava-gemma-2b / openvid1m

[RUN] llava-gemma-2b / pick_a_pic

C:\Users\Samuel\AppData\Roaming\Python\Python314\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Samuel\.cache\huggingface\hub\datasets--kevinkingslin--pick-a-pic. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

[OK] llava-gemma-2b / pick_a_pic

[RUN] llava-gemma-2b / places

[OK] llava-gemma-2b / places

[RUN] llava-gemma-2b / sharegpt4o_image

[OK] llava-gemma-2b / sharegpt4o_image

[RUN] llava-gemma-2b / tad66k

[OK] llava-gemma-2b / tad66k

[RUN] llava-gemma-2b / textcaps

[OK] llava-gemma-2b / textcaps

[RUN] llava-gemma-2b / ucf101

[OK] llava-gemma-2b / ucf101

[RUN] llava-gemma-2b / visual_cot

[OK] llava-gemma-2b / visual_cot

[RUN] llava-gemma-2b / visual_genome

[ERROR] llava-gemma-2b / visual_genome

[RUN] llava-gemma-2b / vqav2

[OK] llava-gemma-2b / vqav2

,model,benchmark,status,error,traceback,num_samples,max_new_tokens,results_path
0,llava-gemma-2b,blip3o_60k,error,ValueError: Could not find two curated attribu...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
1,llava-gemma-2b,conceptual_captions,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
2,llava-gemma-2b,conceptual_captions_caption,ok,NaN,NaN,1.0,24.0,C:\Users\Samuel\Documents\GitHub\transformers\...
3,llava-gemma-2b,cityscapes,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
4,llava-gemma-2b,dfdc,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
5,llava-gemma-2b,diffusiondb,error,RuntimeError: Dataset scripts are no longer su...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
6,llava-gemma-2b,docvqa,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
7,llava-gemma-2b,fairface,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
8,llava-gemma-2b,fashion_mnist,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
9,llava-gemma-2b,flickr30k,ok,NaN,NaN,1.0,24.0,C:\Users\Samuel\Documents\GitHub\transformers\...
10,llava-gemma-2b,flickr30k_entities,ok,NaN,NaN,1.0,32.0,C:\Users\Samuel\Documents\GitHub\transformers\...
11,llava-gemma-2b,flyingthings3d,error,ValueError: Could not find image data in row f...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
12,llava-gemma-2b,gqa,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
13,llava-gemma-2b,hdtf,error,DatasetNotFoundError: Dataset 'HDTF/HDTF' does...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
14,llava-gemma-2b,hq_edit,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
15,llava-gemma-2b,imagenet1k,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
16,llava-gemma-2b,imgedit,error,DatasetNotFoundError: Dataset 'ImagenHub/ImgEd...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
17,llava-gemma-2b,inaturalist,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
18,llava-gemma-2b,internvid,error,DatasetNotFoundError: Dataset 'OpenGVLab/Inter...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
19,llava-gemma-2b,kinetics,error,DatasetNotFoundError: Dataset 'google/kinetics...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
20,llava-gemma-2b,laion400m,error,DatasetNotFoundError: Dataset 'laion/laion400m...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
21,llava-gemma-2b,laion5b,error,DatasetNotFoundError: Dataset 'laion/laion5b' ...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
22,llava-gemma-2b,lsun,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
23,llava-gemma-2b,lvis,error,RuntimeError: Dataset scripts are no longer su...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
24,llava-gemma-2b,mscoco,ok,NaN,NaN,1.0,32.0,C:\Users\Samuel\Documents\GitHub\transformers\...
25,llava-gemma-2b,mscoco_caption,ok,NaN,NaN,1.0,32.0,C:\Users\Samuel\Documents\GitHub\transformers\...
26,llava-gemma-2b,mvtec_ad,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
27,llava-gemma-2b,magicbrush,error,ValueError: Could not find image data in row f...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
28,llava-gemma-2b,openimages_v4,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
29,llava-gemma-2b,openimages_v4_detection,ok,NaN,NaN,1.0,32.0,C:\Users\Samuel\Documents\GitHub\transformers\...
30,llava-gemma-2b,openvid1m,error,DatasetNotFoundError: Dataset 'OpenGVLab/OpenV...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
31,llava-gemma-2b,pick_a_pic,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
32,llava-gemma-2b,places,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
33,llava-gemma-2b,sharegpt4o_image,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
34,llava-gemma-2b,tad66k,ok,NaN,NaN,1.0,4.0,C:\Users\Samuel\Documents\GitHub\transformers\...
35,llava-gemma-2b,textcaps,ok,NaN,NaN,1.0,24.0,C:\Users\Samuel\Documents\GitHub\transformers\...
36,llava-gemma-2b,ucf101,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
37,llava-gemma-2b,visual_cot,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
38,llava-gemma-2b,visual_genome,error,RuntimeError: Dataset scripts are no longer su...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
39,llava-gemma-2b,vqav2,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...

## 5. Inspect aggregate results

In [5]:
rows = []
for path in sorted(OUTPUT_DIR.glob("*.json")):
    if path == SUMMARY_PATH:
        continue
    payload = json.loads(path.read_text(encoding="utf-8"))
    report = payload["report"]
    stats = report.get("stats", {})
    rows.append(
        {
            "model": payload["model"],
            "benchmark": payload["benchmark"],
            "samples": report.get("num_samples"),
            "success_count": stats.get("success_count"),
            "failure_count": stats.get("failure_count"),
            "wall_clock_seconds": stats.get("wall_clock_time_seconds"),
            "result_path": str(path),
        }
    )

results_df = pd.DataFrame(rows)
display(results_df)

run_status_df = pd.DataFrame(json.loads(SUMMARY_PATH.read_text(encoding="utf-8")))
run_status_df

,model,benchmark,samples,success_count,failure_count,wall_clock_seconds,result_path
0,dataset-smoke-model,cityscapes,1,1,0,0.065927,C:\Users\Samuel\Documents\GitHub\transformers\...
1,dataset-smoke-model,conceptual_captions,1,1,0,0.742977,C:\Users\Samuel\Documents\GitHub\transformers\...
2,dataset-smoke-model,conceptual_captions_caption,1,1,0,0.361234,C:\Users\Samuel\Documents\GitHub\transformers\...
3,dataset-smoke-model,dfdc,1,1,0,0.070502,C:\Users\Samuel\Documents\GitHub\transformers\...
4,dataset-smoke-model,docvqa,1,1,0,0.057196,C:\Users\Samuel\Documents\GitHub\transformers\...
5,dataset-smoke-model,fairface,1,1,0,0.051824,C:\Users\Samuel\Documents\GitHub\transformers\...
6,dataset-smoke-model,fashion_mnist,1,1,0,0.055268,C:\Users\Samuel\Documents\GitHub\transformers\...
7,dataset-smoke-model,flickr30k,1,1,0,0.052513,C:\Users\Samuel\Documents\GitHub\transformers\...
8,dataset-smoke-model,flickr30k_entities,1,1,0,0.052831,C:\Users\Samuel\Documents\GitHub\transformers\...
9,llava-gemma-2b,cityscapes,1,1,0,70.797038,C:\Users\Samuel\Documents\GitHub\transformers\...
10,llava-gemma-2b,conceptual_captions,1,1,0,70.435328,C:\Users\Samuel\Documents\GitHub\transformers\...
11,llava-gemma-2b,conceptual_captions_caption,1,1,0,71.088754,C:\Users\Samuel\Documents\GitHub\transformers\...
12,llava-gemma-2b,dfdc,1,1,0,67.246627,C:\Users\Samuel\Documents\GitHub\transformers\...
13,llava-gemma-2b,docvqa,1,1,0,67.958229,C:\Users\Samuel\Documents\GitHub\transformers\...
14,llava-gemma-2b,fairface,1,1,0,71.190093,C:\Users\Samuel\Documents\GitHub\transformers\...
15,llava-gemma-2b,fashion_mnist,1,1,0,68.607707,C:\Users\Samuel\Documents\GitHub\transformers\...
16,llava-gemma-2b,flickr30k,1,1,0,65.895767,C:\Users\Samuel\Documents\GitHub\transformers\...
17,llava-gemma-2b,flickr30k_entities,1,1,0,74.123079,C:\Users\Samuel\Documents\GitHub\transformers\...
18,llava-gemma-2b,gqa,1,1,0,61.214460,C:\Users\Samuel\Documents\GitHub\transformers\...
19,llava-gemma-2b,hq_edit,1,1,0,70.430875,C:\Users\Samuel\Documents\GitHub\transformers\...
20,llava-gemma-2b,imagenet1k,1,1,0,62.479386,C:\Users\Samuel\Documents\GitHub\transformers\...
21,llava-gemma-2b,inaturalist,1,1,0,64.405974,C:\Users\Samuel\Documents\GitHub\transformers\...
22,llava-gemma-2b,lsun,1,1,0,65.849923,C:\Users\Samuel\Documents\GitHub\transformers\...
23,llava-gemma-2b,mscoco,1,1,0,427.181455,C:\Users\Samuel\Documents\GitHub\transformers\...
24,llava-gemma-2b,mscoco_caption,1,1,0,66.011266,C:\Users\Samuel\Documents\GitHub\transformers\...
25,llava-gemma-2b,mvtec_ad,1,1,0,62.431892,C:\Users\Samuel\Documents\GitHub\transformers\...
26,llava-gemma-2b,openimages_v4,1,1,0,63.271526,C:\Users\Samuel\Documents\GitHub\transformers\...
27,llava-gemma-2b,openimages_v4_detection,1,1,0,71.805297,C:\Users\Samuel\Documents\GitHub\transformers\...
28,llava-gemma-2b,pick_a_pic,1,1,0,64.391113,C:\Users\Samuel\Documents\GitHub\transformers\...
29,llava-gemma-2b,places,1,1,0,67.816281,C:\Users\Samuel\Documents\GitHub\transformers\...
30,llava-gemma-2b,sharegpt4o_image,1,1,0,196.805927,C:\Users\Samuel\Documents\GitHub\transformers\...
31,llava-gemma-2b,tad66k,1,1,0,70.699898,C:\Users\Samuel\Documents\GitHub\transformers\...
32,llava-gemma-2b,textcaps,1,1,0,66.178757,C:\Users\Samuel\Documents\GitHub\transformers\...
33,llava-gemma-2b,ucf101,1,1,0,65.738171,C:\Users\Samuel\Documents\GitHub\transformers\...
34,llava-gemma-2b,visual_cot,1,0,1,0.000323,C:\Users\Samuel\Documents\GitHub\transformers\...
35,llava-gemma-2b,vqav2,1,1,0,62.964847,C:\Users\Samuel\Documents\GitHub\transformers\...

,model,benchmark,status,error,traceback,num_samples,max_new_tokens,results_path
0,llava-gemma-2b,blip3o_60k,error,ValueError: Could not find two curated attribu...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
1,llava-gemma-2b,conceptual_captions,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
2,llava-gemma-2b,conceptual_captions_caption,ok,NaN,NaN,1.0,24.0,C:\Users\Samuel\Documents\GitHub\transformers\...
3,llava-gemma-2b,cityscapes,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
4,llava-gemma-2b,dfdc,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
5,llava-gemma-2b,diffusiondb,error,RuntimeError: Dataset scripts are no longer su...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
6,llava-gemma-2b,docvqa,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
7,llava-gemma-2b,fairface,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
8,llava-gemma-2b,fashion_mnist,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
9,llava-gemma-2b,flickr30k,ok,NaN,NaN,1.0,24.0,C:\Users\Samuel\Documents\GitHub\transformers\...
10,llava-gemma-2b,flickr30k_entities,ok,NaN,NaN,1.0,32.0,C:\Users\Samuel\Documents\GitHub\transformers\...
11,llava-gemma-2b,flyingthings3d,error,ValueError: Could not find image data in row f...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
12,llava-gemma-2b,gqa,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
13,llava-gemma-2b,hdtf,error,DatasetNotFoundError: Dataset 'HDTF/HDTF' does...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
14,llava-gemma-2b,hq_edit,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
15,llava-gemma-2b,imagenet1k,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
16,llava-gemma-2b,imgedit,error,DatasetNotFoundError: Dataset 'ImagenHub/ImgEd...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
17,llava-gemma-2b,inaturalist,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
18,llava-gemma-2b,internvid,error,DatasetNotFoundError: Dataset 'OpenGVLab/Inter...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
19,llava-gemma-2b,kinetics,error,DatasetNotFoundError: Dataset 'google/kinetics...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
20,llava-gemma-2b,laion400m,error,DatasetNotFoundError: Dataset 'laion/laion400m...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
21,llava-gemma-2b,laion5b,error,DatasetNotFoundError: Dataset 'laion/laion5b' ...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
22,llava-gemma-2b,lsun,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
23,llava-gemma-2b,lvis,error,RuntimeError: Dataset scripts are no longer su...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
24,llava-gemma-2b,mscoco,ok,NaN,NaN,1.0,32.0,C:\Users\Samuel\Documents\GitHub\transformers\...
25,llava-gemma-2b,mscoco_caption,ok,NaN,NaN,1.0,32.0,C:\Users\Samuel\Documents\GitHub\transformers\...
26,llava-gemma-2b,mvtec_ad,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
27,llava-gemma-2b,magicbrush,error,ValueError: Could not find image data in row f...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
28,llava-gemma-2b,openimages_v4,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
29,llava-gemma-2b,openimages_v4_detection,ok,NaN,NaN,1.0,32.0,C:\Users\Samuel\Documents\GitHub\transformers\...
30,llava-gemma-2b,openvid1m,error,DatasetNotFoundError: Dataset 'OpenGVLab/OpenV...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
31,llava-gemma-2b,pick_a_pic,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
32,llava-gemma-2b,places,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
33,llava-gemma-2b,sharegpt4o_image,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
34,llava-gemma-2b,tad66k,ok,NaN,NaN,1.0,4.0,C:\Users\Samuel\Documents\GitHub\transformers\...
35,llava-gemma-2b,textcaps,ok,NaN,NaN,1.0,24.0,C:\Users\Samuel\Documents\GitHub\transformers\...
36,llava-gemma-2b,ucf101,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
37,llava-gemma-2b,visual_cot,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...
38,llava-gemma-2b,visual_genome,error,RuntimeError: Dataset scripts are no longer su...,"Traceback (most recent call last):\n File ""C:...",NaN,NaN,NaN
39,llava-gemma-2b,vqav2,ok,NaN,NaN,1.0,16.0,C:\Users\Samuel\Documents\GitHub\transformers\...